#!/bin/bash

set -e

APP_NAME="score-system"
APP_DIR="/opt/$APP_NAME"
DATA_DIR="$APP_DIR/data"
SERVICE_FILE="/etc/systemd/system/$APP_NAME.service"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_dependencies() {
    log_info "Checking dependencies..."
    
    local missing=()
    
    if ! command -v go &> /dev/null; then
        missing+=("go")
    fi
    
    if ! command -v bun &> /dev/null && ! command -v npm &> /dev/null; then
        missing+=("bun or npm")
    fi
    
    if ! command -v git &> /dev/null; then
        missing+=("git")
    fi
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies: ${missing[*]}"
        log_info "Install them first:"
        log_info "  apt install golang-go git"
        log_info "  curl -fsSL https://bun.sh/install | bash"
        exit 1
    fi
    
    log_info "All dependencies satisfied"
}

get_inputs() {
    echo ""
    echo "======================================"
    echo "  Score System Installer"
    echo "======================================"
    echo ""
    
    read -p "Enter your domain (e.g., scores.example.com): " DOMAIN
    
    while [[ -z "$DOMAIN" ]]; do
        log_error "Domain is required"
        read -p "Enter your domain: " DOMAIN
    done
    
    read -p "Enter git repository URL: " GIT_REPO
    
    while [[ -z "$GIT_REPO" ]]; do
        log_error "Git repository URL is required"
        read -p "Enter git repository URL: " GIT_REPO
    done
    
    echo ""
}

create_user() {
    log_info "Creating $APP_NAME user..."
    
    if id "$APP_NAME" &>/dev/null; then
        log_warn "User $APP_NAME already exists"
    else
        useradd --system --no-create-home --shell /bin/false "$APP_NAME"
        log_info "User $APP_NAME created"
    fi
}

clone_repo() {
    log_info "Cloning repository..."
    
    if [[ -d "$APP_DIR" ]]; then
        log_warn "$APP_DIR already exists"
        read -p "Remove and re-clone? (y/N): " confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            rm -rf "$APP_DIR"
        else
            log_info "Using existing directory"
            return
        fi
    fi
    
    git clone "$GIT_REPO" "$APP_DIR"
    log_info "Repository cloned to $APP_DIR"
}

create_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$DATA_DIR"
    log_info "Created $DATA_DIR"
}

generate_jwt_secret() {
    JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    log_info "Generated JWT secret"
}

create_env_file() {
    log_info "Creating environment file..."
    
    ENV_FILE="$APP_DIR/.env"
    
    if [[ -f "$ENV_FILE" ]]; then
        log_warn ".env file already exists, backing up..."
        mv "$ENV_FILE" "$ENV_FILE.bak"
    fi
    
    cat > "$ENV_FILE" << EOF
# Score System Configuration
# Generated by install script

# Server port
PORT=8080

# Database path (SQLite)
DATABASE_URL=$DATA_DIR/score.db

# JWT secret (keep this secure!)
JWT_SECRET=$JWT_SECRET

# Frontend dist directory (relative to app dir)
FRONTEND_DIST=dist

# Frontend URL (leave empty for same-origin deployment)
FRONTEND_URL=

# Domain (for reference)
# DOMAIN=$DOMAIN
EOF
    
    log_info "Created $ENV_FILE"
}

install_dependencies() {
    log_info "Installing dependencies..."
    
    cd "$APP_DIR"
    
    if command -v bun &> /dev/null; then
        bun install
    else
        npm install
    fi
    
    log_info "Dependencies installed"
}

build_frontend() {
    log_info "Building frontend..."
    
    cd "$APP_DIR"
    
    if command -v bun &> /dev/null; then
        bun run build
    else
        npm run build
    fi
    
    log_info "Frontend built"
}

build_backend() {
    log_info "Building backend..."
    
    cd "$APP_DIR/backend"
    
    go build -ldflags="-s -w" -o "../dist/server" main.go
    
    log_info "Backend built"
    
    cd "$APP_DIR/backend"
    go build -ldflags="-s -w" -o "../dist/seed" cmd/seed/main.go
    
    log_info "Seed binary built"
}

set_permissions() {
    log_info "Setting permissions..."
    
    chown -R "$APP_NAME:$APP_NAME" "$APP_DIR"
    chmod 700 "$APP_DIR"
    chmod 700 "$DATA_DIR"
    chmod 600 "$APP_DIR/.env"
    
    log_info "Permissions set"
}

install_service() {
    log_info "Installing systemd service..."
    
    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Score System
After=network.target

[Service]
Type=simple
User=$APP_NAME
Group=$APP_NAME
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$APP_DIR/dist/server
Restart=on-failure
RestartSec=5

# Security
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$APP_DIR

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable "$APP_NAME"
    
    log_info "Service installed"
}

start_service() {
    log_info "Starting service..."
    
    systemctl start "$APP_NAME"
    sleep 2
    
    if systemctl is-active --quiet "$APP_NAME"; then
        log_info "Service started successfully"
    else
        log_error "Service failed to start"
        journalctl -u "$APP_NAME" --no-pager -n 20
        exit 1
    fi
}

print_summary() {
    echo ""
    echo "======================================"
    echo -e "${GREEN}  Installation Complete!${NC}"
    echo "======================================"
    echo ""
    echo "Your Score System is installed at:"
    echo "  $APP_DIR"
    echo ""
    echo "The service is running on port 8080."
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Create an admin user:"
    echo "   sudo -u $APP_NAME $APP_DIR/dist/seed"
    echo ""
    echo "2. Configure Traefik to proxy to http://127.0.0.1:8080"
    echo "   with Host rule: $DOMAIN"
    echo ""
    echo "3. Access your Score System at:"
    echo "   https://$DOMAIN"
    echo ""
    echo "Useful commands:"
    echo "  Status:  systemctl status $APP_NAME"
    echo "  Logs:    journalctl -u $APP_NAME -f"
    echo "  Restart: systemctl restart $APP_NAME"
    echo "  Update:  $APP_DIR/deploy/update.sh"
    echo ""
}

main() {
    check_root
    check_dependencies
    get_inputs
    create_user
    clone_repo
    create_directories
    generate_jwt_secret
    create_env_file
    install_dependencies
    build_frontend
    build_backend
    set_permissions
    install_service
    start_service
    print_summary
}

main "$@"
